/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as R505RouteImport } from './routes/505'
import { Route as R422RouteImport } from './routes/422'
import { Route as R403RouteImport } from './routes/403'
import { Route as R401RouteImport } from './routes/401'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard/history'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as Dashboard505RouteImport } from './routes/dashboard/505'
import { Route as Dashboard404RouteImport } from './routes/dashboard/404'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as DashboardProjectSettingsRouteRouteImport } from './routes/dashboard/project-settings/route'
import { Route as DashboardClientsRouteRouteImport } from './routes/dashboard/clients/route'
import { Route as DashboardAgentsRouteRouteImport } from './routes/dashboard/agents/route'
import { Route as DashboardProjectSettingsIndexRouteImport } from './routes/dashboard/project-settings/index'
import { Route as DashboardPhoneIndexRouteImport } from './routes/dashboard/phone/index'
import { Route as DashboardClientsIndexRouteImport } from './routes/dashboard/clients/index'
import { Route as DashboardAgentsIndexRouteImport } from './routes/dashboard/agents/index'
import { Route as DashboardProjectSettingsVoiceRouteImport } from './routes/dashboard/project-settings/voice'
import { Route as DashboardProjectSettingsPreviewRouteImport } from './routes/dashboard/project-settings/preview'
import { Route as DashboardProjectSettingsAgentRouteImport } from './routes/dashboard/project-settings/agent'
import { Route as DashboardPhoneIdRouteImport } from './routes/dashboard/phone/$id'
import { Route as DashboardHistoryConversationRouteImport } from './routes/dashboard/history.$conversation'
import { Route as DashboardAgents505RouteImport } from './routes/dashboard/agents/505'
import { Route as DashboardAgents404RouteImport } from './routes/dashboard/agents/404'
import { Route as DashboardAgentsAgentRouteRouteImport } from './routes/dashboard/agents/$agent/route'
import { Route as DashboardAgentsAgentIndexRouteImport } from './routes/dashboard/agents/$agent/index'
import { Route as DashboardAgentsAgentVoiceRouteImport } from './routes/dashboard/agents/$agent/voice'
import { Route as DashboardAgentsAgentPreviewRouteImport } from './routes/dashboard/agents/$agent/preview'
import { Route as DashboardAgentsAgentAgentRouteImport } from './routes/dashboard/agents/$agent/agent'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const R505Route = R505RouteImport.update({
  id: '/505',
  path: '/505',
  getParentRoute: () => rootRouteImport,
} as any)
const R422Route = R422RouteImport.update({
  id: '/422',
  path: '/422',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const R401Route = R401RouteImport.update({
  id: '/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const Dashboard505Route = Dashboard505RouteImport.update({
  id: '/505',
  path: '/505',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const Dashboard404Route = Dashboard404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectSettingsRouteRoute =
  DashboardProjectSettingsRouteRouteImport.update({
    id: '/project-settings',
    path: '/project-settings',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardClientsRouteRoute = DashboardClientsRouteRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgentsRouteRoute = DashboardAgentsRouteRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectSettingsIndexRoute =
  DashboardProjectSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectSettingsRouteRoute,
  } as any)
const DashboardPhoneIndexRoute = DashboardPhoneIndexRouteImport.update({
  id: '/phone/',
  path: '/phone/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClientsIndexRoute = DashboardClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardClientsRouteRoute,
} as any)
const DashboardAgentsIndexRoute = DashboardAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAgentsRouteRoute,
} as any)
const DashboardProjectSettingsVoiceRoute =
  DashboardProjectSettingsVoiceRouteImport.update({
    id: '/voice',
    path: '/voice',
    getParentRoute: () => DashboardProjectSettingsRouteRoute,
  } as any)
const DashboardProjectSettingsPreviewRoute =
  DashboardProjectSettingsPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => DashboardProjectSettingsRouteRoute,
  } as any)
const DashboardProjectSettingsAgentRoute =
  DashboardProjectSettingsAgentRouteImport.update({
    id: '/agent',
    path: '/agent',
    getParentRoute: () => DashboardProjectSettingsRouteRoute,
  } as any)
const DashboardPhoneIdRoute = DashboardPhoneIdRouteImport.update({
  id: '/phone/$id',
  path: '/phone/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHistoryConversationRoute =
  DashboardHistoryConversationRouteImport.update({
    id: '/$conversation',
    path: '/$conversation',
    getParentRoute: () => DashboardHistoryRoute,
  } as any)
const DashboardAgents505Route = DashboardAgents505RouteImport.update({
  id: '/505',
  path: '/505',
  getParentRoute: () => DashboardAgentsRouteRoute,
} as any)
const DashboardAgents404Route = DashboardAgents404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => DashboardAgentsRouteRoute,
} as any)
const DashboardAgentsAgentRouteRoute =
  DashboardAgentsAgentRouteRouteImport.update({
    id: '/$agent',
    path: '/$agent',
    getParentRoute: () => DashboardAgentsRouteRoute,
  } as any)
const DashboardAgentsAgentIndexRoute =
  DashboardAgentsAgentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAgentsAgentRouteRoute,
  } as any)
const DashboardAgentsAgentVoiceRoute =
  DashboardAgentsAgentVoiceRouteImport.update({
    id: '/voice',
    path: '/voice',
    getParentRoute: () => DashboardAgentsAgentRouteRoute,
  } as any)
const DashboardAgentsAgentPreviewRoute =
  DashboardAgentsAgentPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => DashboardAgentsAgentRouteRoute,
  } as any)
const DashboardAgentsAgentAgentRoute =
  DashboardAgentsAgentAgentRouteImport.update({
    id: '/agent',
    path: '/agent',
    getParentRoute: () => DashboardAgentsAgentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/422': typeof R422Route
  '/505': typeof R505Route
  '/pricing': typeof PricingRoute
  '/dashboard/agents': typeof DashboardAgentsRouteRouteWithChildren
  '/dashboard/clients': typeof DashboardClientsRouteRouteWithChildren
  '/dashboard/project-settings': typeof DashboardProjectSettingsRouteRouteWithChildren
  '/register': typeof authRegisterRoute
  '/sign-in': typeof authSignInRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/dashboard/404': typeof Dashboard404Route
  '/dashboard/505': typeof Dashboard505Route
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/history': typeof DashboardHistoryRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/agents/$agent': typeof DashboardAgentsAgentRouteRouteWithChildren
  '/dashboard/agents/404': typeof DashboardAgents404Route
  '/dashboard/agents/505': typeof DashboardAgents505Route
  '/dashboard/history/$conversation': typeof DashboardHistoryConversationRoute
  '/dashboard/phone/$id': typeof DashboardPhoneIdRoute
  '/dashboard/project-settings/agent': typeof DashboardProjectSettingsAgentRoute
  '/dashboard/project-settings/preview': typeof DashboardProjectSettingsPreviewRoute
  '/dashboard/project-settings/voice': typeof DashboardProjectSettingsVoiceRoute
  '/dashboard/agents/': typeof DashboardAgentsIndexRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/phone/': typeof DashboardPhoneIndexRoute
  '/dashboard/project-settings/': typeof DashboardProjectSettingsIndexRoute
  '/dashboard/agents/$agent/agent': typeof DashboardAgentsAgentAgentRoute
  '/dashboard/agents/$agent/preview': typeof DashboardAgentsAgentPreviewRoute
  '/dashboard/agents/$agent/voice': typeof DashboardAgentsAgentVoiceRoute
  '/dashboard/agents/$agent/': typeof DashboardAgentsAgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/422': typeof R422Route
  '/505': typeof R505Route
  '/pricing': typeof PricingRoute
  '/register': typeof authRegisterRoute
  '/sign-in': typeof authSignInRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/dashboard/404': typeof Dashboard404Route
  '/dashboard/505': typeof Dashboard505Route
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/history': typeof DashboardHistoryRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/agents/404': typeof DashboardAgents404Route
  '/dashboard/agents/505': typeof DashboardAgents505Route
  '/dashboard/history/$conversation': typeof DashboardHistoryConversationRoute
  '/dashboard/phone/$id': typeof DashboardPhoneIdRoute
  '/dashboard/project-settings/agent': typeof DashboardProjectSettingsAgentRoute
  '/dashboard/project-settings/preview': typeof DashboardProjectSettingsPreviewRoute
  '/dashboard/project-settings/voice': typeof DashboardProjectSettingsVoiceRoute
  '/dashboard/agents': typeof DashboardAgentsIndexRoute
  '/dashboard/clients': typeof DashboardClientsIndexRoute
  '/dashboard/phone': typeof DashboardPhoneIndexRoute
  '/dashboard/project-settings': typeof DashboardProjectSettingsIndexRoute
  '/dashboard/agents/$agent/agent': typeof DashboardAgentsAgentAgentRoute
  '/dashboard/agents/$agent/preview': typeof DashboardAgentsAgentPreviewRoute
  '/dashboard/agents/$agent/voice': typeof DashboardAgentsAgentVoiceRoute
  '/dashboard/agents/$agent': typeof DashboardAgentsAgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/422': typeof R422Route
  '/505': typeof R505Route
  '/pricing': typeof PricingRoute
  '/dashboard/agents': typeof DashboardAgentsRouteRouteWithChildren
  '/dashboard/clients': typeof DashboardClientsRouteRouteWithChildren
  '/dashboard/project-settings': typeof DashboardProjectSettingsRouteRouteWithChildren
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/dashboard/404': typeof Dashboard404Route
  '/dashboard/505': typeof Dashboard505Route
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/history': typeof DashboardHistoryRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/agents/$agent': typeof DashboardAgentsAgentRouteRouteWithChildren
  '/dashboard/agents/404': typeof DashboardAgents404Route
  '/dashboard/agents/505': typeof DashboardAgents505Route
  '/dashboard/history/$conversation': typeof DashboardHistoryConversationRoute
  '/dashboard/phone/$id': typeof DashboardPhoneIdRoute
  '/dashboard/project-settings/agent': typeof DashboardProjectSettingsAgentRoute
  '/dashboard/project-settings/preview': typeof DashboardProjectSettingsPreviewRoute
  '/dashboard/project-settings/voice': typeof DashboardProjectSettingsVoiceRoute
  '/dashboard/agents/': typeof DashboardAgentsIndexRoute
  '/dashboard/clients/': typeof DashboardClientsIndexRoute
  '/dashboard/phone/': typeof DashboardPhoneIndexRoute
  '/dashboard/project-settings/': typeof DashboardProjectSettingsIndexRoute
  '/dashboard/agents/$agent/agent': typeof DashboardAgentsAgentAgentRoute
  '/dashboard/agents/$agent/preview': typeof DashboardAgentsAgentPreviewRoute
  '/dashboard/agents/$agent/voice': typeof DashboardAgentsAgentVoiceRoute
  '/dashboard/agents/$agent/': typeof DashboardAgentsAgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/401'
    | '/403'
    | '/422'
    | '/505'
    | '/pricing'
    | '/dashboard/agents'
    | '/dashboard/clients'
    | '/dashboard/project-settings'
    | '/register'
    | '/sign-in'
    | '/agents/$agentId'
    | '/dashboard/404'
    | '/dashboard/505'
    | '/dashboard/analytics'
    | '/dashboard/history'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/agents/$agent'
    | '/dashboard/agents/404'
    | '/dashboard/agents/505'
    | '/dashboard/history/$conversation'
    | '/dashboard/phone/$id'
    | '/dashboard/project-settings/agent'
    | '/dashboard/project-settings/preview'
    | '/dashboard/project-settings/voice'
    | '/dashboard/agents/'
    | '/dashboard/clients/'
    | '/dashboard/phone/'
    | '/dashboard/project-settings/'
    | '/dashboard/agents/$agent/agent'
    | '/dashboard/agents/$agent/preview'
    | '/dashboard/agents/$agent/voice'
    | '/dashboard/agents/$agent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/401'
    | '/403'
    | '/422'
    | '/505'
    | '/pricing'
    | '/register'
    | '/sign-in'
    | '/agents/$agentId'
    | '/dashboard/404'
    | '/dashboard/505'
    | '/dashboard/analytics'
    | '/dashboard/history'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/agents/404'
    | '/dashboard/agents/505'
    | '/dashboard/history/$conversation'
    | '/dashboard/phone/$id'
    | '/dashboard/project-settings/agent'
    | '/dashboard/project-settings/preview'
    | '/dashboard/project-settings/voice'
    | '/dashboard/agents'
    | '/dashboard/clients'
    | '/dashboard/phone'
    | '/dashboard/project-settings'
    | '/dashboard/agents/$agent/agent'
    | '/dashboard/agents/$agent/preview'
    | '/dashboard/agents/$agent/voice'
    | '/dashboard/agents/$agent'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/401'
    | '/403'
    | '/422'
    | '/505'
    | '/pricing'
    | '/dashboard/agents'
    | '/dashboard/clients'
    | '/dashboard/project-settings'
    | '/(auth)/register'
    | '/(auth)/sign-in'
    | '/agents/$agentId'
    | '/dashboard/404'
    | '/dashboard/505'
    | '/dashboard/analytics'
    | '/dashboard/history'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/agents/$agent'
    | '/dashboard/agents/404'
    | '/dashboard/agents/505'
    | '/dashboard/history/$conversation'
    | '/dashboard/phone/$id'
    | '/dashboard/project-settings/agent'
    | '/dashboard/project-settings/preview'
    | '/dashboard/project-settings/voice'
    | '/dashboard/agents/'
    | '/dashboard/clients/'
    | '/dashboard/phone/'
    | '/dashboard/project-settings/'
    | '/dashboard/agents/$agent/agent'
    | '/dashboard/agents/$agent/preview'
    | '/dashboard/agents/$agent/voice'
    | '/dashboard/agents/$agent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  R401Route: typeof R401Route
  R403Route: typeof R403Route
  R422Route: typeof R422Route
  R505Route: typeof R505Route
  PricingRoute: typeof PricingRoute
  authRegisterRoute: typeof authRegisterRoute
  authSignInRoute: typeof authSignInRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/505': {
      id: '/505'
      path: '/505'
      fullPath: '/505'
      preLoaderRoute: typeof R505RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/422': {
      id: '/422'
      path: '/422'
      fullPath: '/422'
      preLoaderRoute: typeof R422RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/401': {
      id: '/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof R401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/505': {
      id: '/dashboard/505'
      path: '/505'
      fullPath: '/dashboard/505'
      preLoaderRoute: typeof Dashboard505RouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/404': {
      id: '/dashboard/404'
      path: '/404'
      fullPath: '/dashboard/404'
      preLoaderRoute: typeof Dashboard404RouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project-settings': {
      id: '/dashboard/project-settings'
      path: '/project-settings'
      fullPath: '/dashboard/project-settings'
      preLoaderRoute: typeof DashboardProjectSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/project-settings/': {
      id: '/dashboard/project-settings/'
      path: '/'
      fullPath: '/dashboard/project-settings/'
      preLoaderRoute: typeof DashboardProjectSettingsIndexRouteImport
      parentRoute: typeof DashboardProjectSettingsRouteRoute
    }
    '/dashboard/phone/': {
      id: '/dashboard/phone/'
      path: '/phone'
      fullPath: '/dashboard/phone/'
      preLoaderRoute: typeof DashboardPhoneIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/clients/': {
      id: '/dashboard/clients/'
      path: '/'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof DashboardClientsIndexRouteImport
      parentRoute: typeof DashboardClientsRouteRoute
    }
    '/dashboard/agents/': {
      id: '/dashboard/agents/'
      path: '/'
      fullPath: '/dashboard/agents/'
      preLoaderRoute: typeof DashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardAgentsRouteRoute
    }
    '/dashboard/project-settings/voice': {
      id: '/dashboard/project-settings/voice'
      path: '/voice'
      fullPath: '/dashboard/project-settings/voice'
      preLoaderRoute: typeof DashboardProjectSettingsVoiceRouteImport
      parentRoute: typeof DashboardProjectSettingsRouteRoute
    }
    '/dashboard/project-settings/preview': {
      id: '/dashboard/project-settings/preview'
      path: '/preview'
      fullPath: '/dashboard/project-settings/preview'
      preLoaderRoute: typeof DashboardProjectSettingsPreviewRouteImport
      parentRoute: typeof DashboardProjectSettingsRouteRoute
    }
    '/dashboard/project-settings/agent': {
      id: '/dashboard/project-settings/agent'
      path: '/agent'
      fullPath: '/dashboard/project-settings/agent'
      preLoaderRoute: typeof DashboardProjectSettingsAgentRouteImport
      parentRoute: typeof DashboardProjectSettingsRouteRoute
    }
    '/dashboard/phone/$id': {
      id: '/dashboard/phone/$id'
      path: '/phone/$id'
      fullPath: '/dashboard/phone/$id'
      preLoaderRoute: typeof DashboardPhoneIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/history/$conversation': {
      id: '/dashboard/history/$conversation'
      path: '/$conversation'
      fullPath: '/dashboard/history/$conversation'
      preLoaderRoute: typeof DashboardHistoryConversationRouteImport
      parentRoute: typeof DashboardHistoryRoute
    }
    '/dashboard/agents/505': {
      id: '/dashboard/agents/505'
      path: '/505'
      fullPath: '/dashboard/agents/505'
      preLoaderRoute: typeof DashboardAgents505RouteImport
      parentRoute: typeof DashboardAgentsRouteRoute
    }
    '/dashboard/agents/404': {
      id: '/dashboard/agents/404'
      path: '/404'
      fullPath: '/dashboard/agents/404'
      preLoaderRoute: typeof DashboardAgents404RouteImport
      parentRoute: typeof DashboardAgentsRouteRoute
    }
    '/dashboard/agents/$agent': {
      id: '/dashboard/agents/$agent'
      path: '/$agent'
      fullPath: '/dashboard/agents/$agent'
      preLoaderRoute: typeof DashboardAgentsAgentRouteRouteImport
      parentRoute: typeof DashboardAgentsRouteRoute
    }
    '/dashboard/agents/$agent/': {
      id: '/dashboard/agents/$agent/'
      path: '/'
      fullPath: '/dashboard/agents/$agent/'
      preLoaderRoute: typeof DashboardAgentsAgentIndexRouteImport
      parentRoute: typeof DashboardAgentsAgentRouteRoute
    }
    '/dashboard/agents/$agent/voice': {
      id: '/dashboard/agents/$agent/voice'
      path: '/voice'
      fullPath: '/dashboard/agents/$agent/voice'
      preLoaderRoute: typeof DashboardAgentsAgentVoiceRouteImport
      parentRoute: typeof DashboardAgentsAgentRouteRoute
    }
    '/dashboard/agents/$agent/preview': {
      id: '/dashboard/agents/$agent/preview'
      path: '/preview'
      fullPath: '/dashboard/agents/$agent/preview'
      preLoaderRoute: typeof DashboardAgentsAgentPreviewRouteImport
      parentRoute: typeof DashboardAgentsAgentRouteRoute
    }
    '/dashboard/agents/$agent/agent': {
      id: '/dashboard/agents/$agent/agent'
      path: '/agent'
      fullPath: '/dashboard/agents/$agent/agent'
      preLoaderRoute: typeof DashboardAgentsAgentAgentRouteImport
      parentRoute: typeof DashboardAgentsAgentRouteRoute
    }
  }
}

interface DashboardAgentsAgentRouteRouteChildren {
  DashboardAgentsAgentAgentRoute: typeof DashboardAgentsAgentAgentRoute
  DashboardAgentsAgentPreviewRoute: typeof DashboardAgentsAgentPreviewRoute
  DashboardAgentsAgentVoiceRoute: typeof DashboardAgentsAgentVoiceRoute
  DashboardAgentsAgentIndexRoute: typeof DashboardAgentsAgentIndexRoute
}

const DashboardAgentsAgentRouteRouteChildren: DashboardAgentsAgentRouteRouteChildren =
  {
    DashboardAgentsAgentAgentRoute: DashboardAgentsAgentAgentRoute,
    DashboardAgentsAgentPreviewRoute: DashboardAgentsAgentPreviewRoute,
    DashboardAgentsAgentVoiceRoute: DashboardAgentsAgentVoiceRoute,
    DashboardAgentsAgentIndexRoute: DashboardAgentsAgentIndexRoute,
  }

const DashboardAgentsAgentRouteRouteWithChildren =
  DashboardAgentsAgentRouteRoute._addFileChildren(
    DashboardAgentsAgentRouteRouteChildren,
  )

interface DashboardAgentsRouteRouteChildren {
  DashboardAgentsAgentRouteRoute: typeof DashboardAgentsAgentRouteRouteWithChildren
  DashboardAgents404Route: typeof DashboardAgents404Route
  DashboardAgents505Route: typeof DashboardAgents505Route
  DashboardAgentsIndexRoute: typeof DashboardAgentsIndexRoute
}

const DashboardAgentsRouteRouteChildren: DashboardAgentsRouteRouteChildren = {
  DashboardAgentsAgentRouteRoute: DashboardAgentsAgentRouteRouteWithChildren,
  DashboardAgents404Route: DashboardAgents404Route,
  DashboardAgents505Route: DashboardAgents505Route,
  DashboardAgentsIndexRoute: DashboardAgentsIndexRoute,
}

const DashboardAgentsRouteRouteWithChildren =
  DashboardAgentsRouteRoute._addFileChildren(DashboardAgentsRouteRouteChildren)

interface DashboardClientsRouteRouteChildren {
  DashboardClientsIndexRoute: typeof DashboardClientsIndexRoute
}

const DashboardClientsRouteRouteChildren: DashboardClientsRouteRouteChildren = {
  DashboardClientsIndexRoute: DashboardClientsIndexRoute,
}

const DashboardClientsRouteRouteWithChildren =
  DashboardClientsRouteRoute._addFileChildren(
    DashboardClientsRouteRouteChildren,
  )

interface DashboardProjectSettingsRouteRouteChildren {
  DashboardProjectSettingsAgentRoute: typeof DashboardProjectSettingsAgentRoute
  DashboardProjectSettingsPreviewRoute: typeof DashboardProjectSettingsPreviewRoute
  DashboardProjectSettingsVoiceRoute: typeof DashboardProjectSettingsVoiceRoute
  DashboardProjectSettingsIndexRoute: typeof DashboardProjectSettingsIndexRoute
}

const DashboardProjectSettingsRouteRouteChildren: DashboardProjectSettingsRouteRouteChildren =
  {
    DashboardProjectSettingsAgentRoute: DashboardProjectSettingsAgentRoute,
    DashboardProjectSettingsPreviewRoute: DashboardProjectSettingsPreviewRoute,
    DashboardProjectSettingsVoiceRoute: DashboardProjectSettingsVoiceRoute,
    DashboardProjectSettingsIndexRoute: DashboardProjectSettingsIndexRoute,
  }

const DashboardProjectSettingsRouteRouteWithChildren =
  DashboardProjectSettingsRouteRoute._addFileChildren(
    DashboardProjectSettingsRouteRouteChildren,
  )

interface DashboardHistoryRouteChildren {
  DashboardHistoryConversationRoute: typeof DashboardHistoryConversationRoute
}

const DashboardHistoryRouteChildren: DashboardHistoryRouteChildren = {
  DashboardHistoryConversationRoute: DashboardHistoryConversationRoute,
}

const DashboardHistoryRouteWithChildren =
  DashboardHistoryRoute._addFileChildren(DashboardHistoryRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAgentsRouteRoute: typeof DashboardAgentsRouteRouteWithChildren
  DashboardClientsRouteRoute: typeof DashboardClientsRouteRouteWithChildren
  DashboardProjectSettingsRouteRoute: typeof DashboardProjectSettingsRouteRouteWithChildren
  Dashboard404Route: typeof Dashboard404Route
  Dashboard505Route: typeof Dashboard505Route
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardHistoryRoute: typeof DashboardHistoryRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPhoneIdRoute: typeof DashboardPhoneIdRoute
  DashboardPhoneIndexRoute: typeof DashboardPhoneIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAgentsRouteRoute: DashboardAgentsRouteRouteWithChildren,
  DashboardClientsRouteRoute: DashboardClientsRouteRouteWithChildren,
  DashboardProjectSettingsRouteRoute:
    DashboardProjectSettingsRouteRouteWithChildren,
  Dashboard404Route: Dashboard404Route,
  Dashboard505Route: Dashboard505Route,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardHistoryRoute: DashboardHistoryRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPhoneIdRoute: DashboardPhoneIdRoute,
  DashboardPhoneIndexRoute: DashboardPhoneIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  R401Route: R401Route,
  R403Route: R403Route,
  R422Route: R422Route,
  R505Route: R505Route,
  PricingRoute: PricingRoute,
  authRegisterRoute: authRegisterRoute,
  authSignInRoute: authSignInRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
